### ISSUE TITLE
User not stored in mongodb

### ISSUE THREAD

**Issue by StarAzure** [Ankit628792/Bumble-Clone#1]
Hi Ankit - I modified db.js to
`const uri = `mongodb://localhost:27017/bumble`;`

Connection to db is successful. I create users but they are not getting stored in db.

Would you mind posting an update to the repo if available? Looks like code for api is missing.

Happy to contribute but need to get this running. Thanks

**Comment by Ankit628792** [comment]
The logs are default, they came up with the react-native. However most of the logs are disabled and ignore the current logs. 
Can you share the screen shots where you're getting stucked regarding user registration?

**Comment by StarAzure** [comment]
I was able to fix it after disabling the edumarcsms calls.  I contacted edumarcsms but they did not respond. Also their signup goes to a contact page so it seems shady.
1) Are there any alternatives to edumarcsms ? Do you have any code for login using social such as google/facebook?
2) Many sections seems to be incomplete - Edit profile does not work for example.  Do you have an updated code base?

It will be helpful for users if you add a TODO section of incomplete screens so they don't have to spend time debugging and they can contribute. Thanks !

**Comment by Ankit628792** [comment]
1. We have contacted the edumarcsms, there is some issue in their database. They are trying to fix it, it'll be resolved soon.
2. There is no edit profile and view profile screen, they need be created

Note: this application requires more than 20 environment variables like sendgrid, aws bucket, sms apis, some other secret credentials that we can't share with others and others don't have that sources to get those. This repository is made for the demo application purpose, we are not trying to get any further upgradation in this, we've already done these things in real application like edit profile, chat support etc.
